name: Production Deployment
on:
  push:
    branches: [ "main" ]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: gradle
      - name: Run Tests
        run: ./gradlew test
      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v4
        if: always()
        with:
          report_paths: '**/build/reports/tests/test/TEST-*.xml'
      - name: Build with Gradle
        run: ./gradlew build -x test
      - name: Build Docker Image
        run: docker build -t backend-app:latest .
      - name: Prepare Deployment Package
        run: |
          mkdir -p deploy_dist
          docker save backend-app:latest -o deploy_dist/backend-app.tar
          cp docker-compose.yml deploy_dist/
          sudo chown -R $USER:$USER deploy_dist
          sudo chmod -R 755 deploy_dist
      - name: Copy artifacts to GCP VM via SCP
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.GCP_VM_HOST }}
          username: ${{ secrets.GCP_VM_USERNAME }}
          key: ${{ secrets.GCP_SSH_KEY }}
          source: "deploy_dist/*"
          target: "~/app"
          strip_components: 1
      - name: Executing remote SSH commands to deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.GCP_VM_HOST }}
          username: ${{ secrets.GCP_VM_USERNAME }}
          key: ${{ secrets.GCP_SSH_KEY }}
          script: |
            cd ~/app
            docker load -i backend-app.tar
            rm backend-app.tar
            NEO4J_URI="${{ secrets.PROD_NEO4J_URI }}" \
            NEO4J_USERNAME="${{ secrets.PROD_NEO4J_USER }}" \
            NEO4J_PASSWORD="${{ secrets.PROD_NEO4J_PASSWORD }}" \
            FRONTEND_URL="${{ secrets.PROD_FRONTEND_URL }}" \
            docker compose up -d --force-recreate